name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [7.3, 7.4, '8.0', 8.1, 8.2]
        wpstarter: [1.*]
        testbench: [1.*]
        os: [ubuntu-latest]


    name: PHP ${{ matrix.php }} / WpStarter ${{ matrix.wpstarter }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extension: mbstring, pdo, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: |
          composer require "wp-starter/contracts:${{ matrix.wpstarter }}" "wpstarter/o-testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer require "doctrine/dbal:${{ matrix.dbal }}" --dev --no-interaction --no-update
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Installed dependencies
        run: composer show -D

      - name: Run tests
        run: vendor/bin/phpunit --exclude-group skipped
